### ISSUE TITLE
Clicking the icon for how many games you can play in doesn't work on the first click after refreshing.

### ISSUE THREAD

**Issue by ursi** [playhex/playhex#63]
- refresh the page
- click the icon (nothing happens)
- click the icon again (it works)

You can even click around to other things first. As long as they are not games, the first click, and only the first click, does not work. If you open a game first, then it will work on the first click.

**Comment by alcalyn** [comment]
Ah, I sometimes noticed it, but not tried to find a way to reproduce. Thanks you found this!
