### ISSUE TITLE
Show HexWorld button on unranked games

### ISSUE THREAD

**Issue by ursi** [playhex/playhex#75]
the hexworld button doesn't show up on real-time unranked games. While I don't support having hexworld links for ranked real-time games, I see no reason to not have this in unranked for the people that prefer to play that way.

**Comment by eilvelia** [comment]
There has also been discussion that enabling the hexworld button could be an option (like swap/noswap exists for unranked games currently), perhaps even for ranked games as well.

**Comment by alcalyn** [comment]
The initial issue is easy. Condition on showing has been done before ranked games, so we just need to update it taking account "ranked" parameter.

The option of allow player simulation or not needs model update. Not a big deal though
