### ISSUE TITLE
Dates in the chat can sometimes be off by a day

### ISSUE THREAD

**Issue by ursi** [playhex/playhex#89]
I noticed that my dates in my current games' chats are off by a day, but my opponent said theirs were correct.

**Comment by alcalyn** [comment]
I don't reproduce, those dates are rendered client side from utc date. Send the link of your game where you have the case, and a screenshot to see if I can reproduce with your canada timestamp.

For example: here is how I see a chat from CET (utc+2):

![image](https://github.com/user-attachments/assets/48007e9c-d890-4778-83d3-9f33aa68054a)

and Asia/Tokyo (utc+9);

![image](https://github.com/user-attachments/assets/ed1eb887-1cce-461f-a044-ecfd900164c7)
